services:
  - type: web
    name: banking-backend
    env: java
    rootDir: ./final
    buildCommand: chmod +x mvnw && ./mvnw clean package -DskipTests
    startCommand: java -jar target/*.jar
    envVars:
      - key: PORT
        value: 8080
      - key: SPRING_PROFILES_ACTIVE
        value: production
      - key: JAVA_OPTS
        value: -Xmx512m